#!/usr/bin/env bash
# script installs a ngix and have a file that returns the string "Hello World  inside

apt update
apt install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx restart
